from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


class ESReferenceTool:
    """
    Reads pre-built reference data (products, criteria, choices) from JSON files.
    These files are generated by XtraReferenceService.run() and stored in output/.
    This tool has no ES dependency — it is file-based only.
    """

    def __init__(self) -> None:
        self._output_dir   = Path("output")
        self._products_path = self._output_dir / "products.json"
        self._criteria_path = self._output_dir / "criteria.json"
        self._choices_path  = self._output_dir / "choice.json"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_product(self, product_id: str) -> Optional[Dict[str, Any]]:
        for product in self._load_json(self._products_path):
            if product.get("id") == product_id:
                return product
        return None

    def get_criteria(self, product_id: str) -> List[Dict[str, Any]]:
        return [
            c for c in self._load_json(self._criteria_path)
            if c.get("product_id") == product_id
        ]

    def get_choices_by_criteria(self, criterion_id: str) -> List[Dict[str, Any]]:
        return [
            c for c in self._load_json(self._choices_path)
            if c.get("criteria_id") == criterion_id
        ]

    def get_all_choices_grouped(self) -> Dict[str, List[Dict[str, Any]]]:
        grouped: Dict[str, List[Dict[str, Any]]] = {}
        for choice in self._load_json(self._choices_path):
            cid = choice.get("criteria_id")
            if cid:
                grouped.setdefault(cid, []).append(choice)
        return grouped

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _load_json(self, path: Path) -> List[Dict[str, Any]]:
        if not path.exists():
            return []
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
